### ISSUE TITLE
Feature Request: Add state of Modifier Keys

### ISSUE THREAD

**Issue by wachjose88** [kazysmaster/gnome-shell-extension-lockkeys#30]
For sticky-keys users it would be nice to see the state of the Modifier Keys (ctrl, shift, alt, alt gr, super). Something like http://www.webupd8.org/2014/09/keyboard-modifiers-state-indicator-for.html

Are there any plans to add them?

thanks wachjose

**Comment by choma** [comment]
+1

**Comment by kazysmaster** [comment]
Hi, because of my extremely limited free time I can not promise anything. It requires major changes to the extension, because I'm using a library that exposes only num-lock and caps-lock state changes and it would require to switch to some other lib/component to support modifier keys. Not all libs are available for gnome extensions.

I'll leave this issue open in case I'll bump into something easy to use.
